// flow-typed signature: 2eee022193834b8462e7905c33afc75a
// flow-typed version: <<STUB>>/@bedegaming/bolt-v2_v^1.0.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@bedegaming/bolt-v2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@bedegaming/bolt-v2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@bedegaming/bolt-v2/flow-typed/npm/@babel/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/@babel/core_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/@babel/plugin-proposal-class-properties_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/@babel/plugin-transform-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/@babel/preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/@babel/preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/@bedegaming/spine-player-client-js_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/add_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/axios_v0.18.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/config_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/cross-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-config-standard_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-config-standard-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-node_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-promise_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-standard_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/gh-pages_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/js-yaml-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/parcel-bundler_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/prop-types_v15.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/react-redux_v5.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/react-scripts_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/redux_v4.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/redux-saga_v0.16.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/webpack-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/webpack-node-externals_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/flow-typed/npm/yarn_vx.x.x' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/components/Data/GamesDisplay' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/components/Data/index' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/components/Data/UserSessionDisplay' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/components/Data/WinnersFeedDisplay' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/components/GamesListHO/index' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/components/HeaderHO/index' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/components/LoginHO/index' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/components/ModalsHO/index' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/components/RegistrationHO/index' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/index' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/redux/**ref**bolt_Api_Wrapper' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/redux/**ref**spine_player_client' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/redux/duckFeeds' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/redux/duckGames' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/redux/duckModals' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/redux/duckUserProfile' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/redux/duckUserSession' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/redux/duckUserWallets' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/redux/indexActionCreators' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/redux/indexReducers' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/redux/indexSagas' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/lib/redux/store' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/production/index' {
  declare module.exports: any;
}

declare module '@bedegaming/bolt-v2/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@bedegaming/bolt-v2/flow-typed/npm/@babel/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/@babel/cli_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/@babel/core_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/@babel/core_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/@babel/plugin-proposal-class-properties_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/@babel/plugin-proposal-class-properties_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/@babel/plugin-transform-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/@babel/plugin-transform-runtime_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/@babel/preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/@babel/preset-env_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/@babel/preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/@babel/preset-react_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/@bedegaming/spine-player-client-js_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/@bedegaming/spine-player-client-js_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/add_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/add_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/axios_v0.18.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/axios_v0.18.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/config_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/config_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/cross-env_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/cross-env_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-config-standard_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/eslint-config-standard_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-config-standard-react_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/eslint-config-standard-react_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-node_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-node_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-promise_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-promise_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-standard_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/eslint-plugin-standard_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/gh-pages_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/gh-pages_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/js-yaml-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/js-yaml-loader_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/parcel-bundler_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/parcel-bundler_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/prettier_v1.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/prop-types_v15.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/prop-types_v15.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/react-redux_v5.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/react-redux_v5.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/react-scripts_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/react-scripts_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/redux_v4.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/redux_v4.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/redux-saga_v0.16.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/redux-saga_v0.16.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/webpack_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/webpack-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/webpack-cli_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/webpack-node-externals_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/webpack-node-externals_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/flow-typed/npm/yarn_vx.x.x.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/flow-typed/npm/yarn_vx.x.x'>;
}
declare module '@bedegaming/bolt-v2/lib/components/Data/GamesDisplay.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/components/Data/GamesDisplay'>;
}
declare module '@bedegaming/bolt-v2/lib/components/Data/index.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/components/Data/index'>;
}
declare module '@bedegaming/bolt-v2/lib/components/Data/UserSessionDisplay.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/components/Data/UserSessionDisplay'>;
}
declare module '@bedegaming/bolt-v2/lib/components/Data/WinnersFeedDisplay.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/components/Data/WinnersFeedDisplay'>;
}
declare module '@bedegaming/bolt-v2/lib/components/GamesListHO/index.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/components/GamesListHO/index'>;
}
declare module '@bedegaming/bolt-v2/lib/components/HeaderHO/index.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/components/HeaderHO/index'>;
}
declare module '@bedegaming/bolt-v2/lib/components/LoginHO/index.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/components/LoginHO/index'>;
}
declare module '@bedegaming/bolt-v2/lib/components/ModalsHO/index.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/components/ModalsHO/index'>;
}
declare module '@bedegaming/bolt-v2/lib/components/RegistrationHO/index.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/components/RegistrationHO/index'>;
}
declare module '@bedegaming/bolt-v2/lib/index.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/index'>;
}
declare module '@bedegaming/bolt-v2/lib/redux/**ref**bolt_Api_Wrapper.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/redux/**ref**bolt_Api_Wrapper'>;
}
declare module '@bedegaming/bolt-v2/lib/redux/**ref**spine_player_client.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/redux/**ref**spine_player_client'>;
}
declare module '@bedegaming/bolt-v2/lib/redux/duckFeeds.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/redux/duckFeeds'>;
}
declare module '@bedegaming/bolt-v2/lib/redux/duckGames.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/redux/duckGames'>;
}
declare module '@bedegaming/bolt-v2/lib/redux/duckModals.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/redux/duckModals'>;
}
declare module '@bedegaming/bolt-v2/lib/redux/duckUserProfile.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/redux/duckUserProfile'>;
}
declare module '@bedegaming/bolt-v2/lib/redux/duckUserSession.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/redux/duckUserSession'>;
}
declare module '@bedegaming/bolt-v2/lib/redux/duckUserWallets.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/redux/duckUserWallets'>;
}
declare module '@bedegaming/bolt-v2/lib/redux/indexActionCreators.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/redux/indexActionCreators'>;
}
declare module '@bedegaming/bolt-v2/lib/redux/indexReducers.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/redux/indexReducers'>;
}
declare module '@bedegaming/bolt-v2/lib/redux/indexSagas.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/redux/indexSagas'>;
}
declare module '@bedegaming/bolt-v2/lib/redux/store.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/lib/redux/store'>;
}
declare module '@bedegaming/bolt-v2/production/index.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/production/index'>;
}
declare module '@bedegaming/bolt-v2/webpack.config.js' {
  declare module.exports: $Exports<'@bedegaming/bolt-v2/webpack.config'>;
}
