// flow-typed signature: b342c46c3884d663ff13b6bf72d854a9
// flow-typed version: <<STUB>>/react-on-screen_v^2.0.4/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-on-screen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-on-screen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-on-screen/dist/ReactOnScreen.min' {
  declare module.exports: any;
}

declare module 'react-on-screen/lib/index' {
  declare module.exports: any;
}

declare module 'react-on-screen/lib/TrackVisibility' {
  declare module.exports: any;
}

declare module 'react-on-screen/setupTests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-on-screen/dist/ReactOnScreen.min.js' {
  declare module.exports: $Exports<'react-on-screen/dist/ReactOnScreen.min'>;
}
declare module 'react-on-screen/lib/index.js' {
  declare module.exports: $Exports<'react-on-screen/lib/index'>;
}
declare module 'react-on-screen/lib/TrackVisibility.js' {
  declare module.exports: $Exports<'react-on-screen/lib/TrackVisibility'>;
}
declare module 'react-on-screen/setupTests.js' {
  declare module.exports: $Exports<'react-on-screen/setupTests'>;
}
